# Generated by Django 3.2.10 on 2022-01-08 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workspaces", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notionworkspace",
            name="icon_url",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
