# See https://pre-commit.com for more information
default_language_version:
  # default language version for each language used in the repository
  python: python3.6.9
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.1.0
    hooks:
      # See https://pre-commit.com/hooks.html for more hooks
      - id: check-ast
      - id: check-case-conflict
      - id: check-merge-conflict
      - id: debug-statements
      - id: end-of-file-fixer
      - id: name-tests-test
        args: [ "--django" ]
      - id: trailing-whitespace
  - repo: https://github.com/asottile/seed-isort-config
    rev: v2.2.0
    hooks:
      - id: seed-isort-config
  - repo: https://github.com/asottile/pyupgrade
    rev: v2.31.0
    hooks:
      - id: pyupgrade
        args: [ "--py36-plus", "--py37-plus", "--py38-plus", "--py39-plus" ]
  - repo: https://github.com/pycqa/isort
    rev: 5.10.1
    hooks:
      - id: isort
  - repo: https://github.com/psf/black
    rev: 21.12b0
    hooks:
      - id: black
  - repo: https://github.com/pycqa/bandit
    rev: 1.7.1
    hooks:
      - id: bandit
        args: [ "-iii", "-ll" ]
  - repo: local
    hooks:
      - id: django-test
        name: django-test
        entry: python manage.py test
        always_run: true
        pass_filenames: false
        language: system
#  - repo: https://github.com/pycqa/pylint
#    rev: v2.12.2
#    hooks:
#      - id: pylint
#        exclude: "[a-zA-Z]*/(migrations)/(.)*"
#        args: [ "--load-plugins=pylint_django", "--django-settings-module=app.settings" ]
#        additional_dependencies: [
#            # pylint dependency
#            pylint_django,
#            # runtime dependencies
#            # ...
#        ]
#  - repo: https://github.com/pre-commit/mirrors-mypy
#    rev: v0.931
#    hooks:
#      - id: mypy
#        exclude: "[a-zA-Z]*/(migrations)/(.)*"
#        additional_dependencies: [
#            # mypy dependencies
#            djangorestframework-stubs,
#            django-stubs,
#            # runtime dependencies
#            # ...
#       ]
