# Generated by Django 4.0.1 on 2022-01-20 06:54

import django.core.serializers.json
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="NotionDatabase",
            fields=[
                (
                    "database_id",
                    models.CharField(
                        blank=None,
                        max_length=255,
                        null=None,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "database_name",
                    models.CharField(blank=None, max_length=255, null=None),
                ),
                (
                    "properties_schema_json",
                    models.JSONField(
                        default=dict,
                        encoder=django.core.serializers.json.DjangoJSONEncoder,
                    ),
                ),
            ],
        ),
    ]
