# Generated by Django 3.2 on 2022-03-15 18:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("workspaces", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="NotionDatabase",
            fields=[
                (
                    "notion_id",
                    models.CharField(max_length=255, primary_key=True, serialize=False),
                ),
                ("database_name", models.CharField(max_length=255)),
                (
                    "notion_workspace",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notion_databases",
                        to="workspaces.notionworkspace",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="NotionPropertyMetaData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("notion_id", models.CharField(max_length=255)),
                ("name", models.CharField(max_length=255)),
                ("property_type", models.CharField(max_length=255)),
                (
                    "database",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notion_properties",
                        to="notion_database.notiondatabase",
                    ),
                ),
            ],
        ),
    ]
