# Generated by Django 3.2.10 on 2021-12-29 22:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('django_q', '0014_schedule_cluster'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RecurringTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('cloned_task_notion_id', models.CharField(max_length=255)),
                ('cloned_task_url', models.CharField(max_length=255)),
                ('database_id', models.CharField(max_length=255)),
                ('start_date', models.DateField(default=django.utils.timezone.now)),
                ('start_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('interval', models.CharField(choices=[('1', 'Every Day'), ('7', 'Every 7 Days'), ('30', 'Every 30 Days'), ('365', 'Every 365 Days')], default='1', max_length=30)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to=settings.AUTH_USER_MODEL)),
                ('scheduler_job', models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='related_recurring_task', to='django_q.schedule')),
            ],
        ),
    ]
