# Generated by Django 3.2.10 on 2021-12-16 13:43

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RecurringTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('cloned_task_notion_id', models.CharField(max_length=255)),
                ('cloned_task_url', models.CharField(max_length=255)),
                ('database_id', models.CharField(max_length=255)),
                ('start_date', models.DateField(default=datetime.datetime(2021, 12, 16, 13, 43, 35, 884988))),
                ('interval', models.CharField(choices=[('1', 'Every Day'), ('7', 'Every 7 Days'), ('30', 'Every 30 Days'), ('365', 'Every 365 Days')], default='1', max_length=30)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
