# Generated by Django 3.2.10 on 2021-12-30 22:16

import datetime

from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="recurringtask",
            name="start_time",
            field=models.DateTimeField(
                default=datetime.datetime(2021, 12, 31, 22, 16, 24, 580172, tzinfo=utc)
            ),
        ),
    ]
