# Generated by Django 3.2.10 on 2021-12-30 10:25

import django.core.serializers.json
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recurringtask',
            name='override_properties_json_string',
            field=models.JSONField(default={}, encoder=django.core.serializers.json.DjangoJSONEncoder),
        ),
    ]
