# Generated by Django 3.2.10 on 2021-12-16 13:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recurringtask',
            name='start_date',
            field=models.DateField(default=datetime.datetime(2021, 12, 16, 13, 43, 46, 23726)),
        ),
    ]
