# Generated by Django 3.2.10 on 2022-01-08 18:02

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_alter_recurringtask_start_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recurringtask',
            name='start_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 1, 9, 18, 2, 33, 892478, tzinfo=utc)),
        ),
    ]
