# Generated by Django 3.1.4 on 2021-12-16 14:54

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_auto_20211216_1448'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recurringtask',
            name='start_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
