# Generated by Django 4.0.1 on 2022-01-20 06:54

import datetime

import django.db.models.deletion
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ("notion_database", "0001_initial"),
        ("tasks", "0004_alter_recurringtask_start_time"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="recurringtask",
            name="database_id",
        ),
        migrations.RemoveField(
            model_name="recurringtask",
            name="database_name",
        ),
        migrations.RemoveField(
            model_name="recurringtask",
            name="owner",
        ),
        migrations.AddField(
            model_name="recurringtask",
            name="database",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="notion_database.notiondatabase",
            ),
        ),
        migrations.AlterField(
            model_name="recurringtask",
            name="start_time",
            field=models.DateTimeField(
                default=datetime.datetime(2022, 1, 21, 6, 54, 36, 559062, tzinfo=utc)
            ),
        ),
    ]
