# Generated by Django 3.2.10 on 2021-12-16 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_auto_20211216_1454'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recurringtask',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
