# Generated by Django 4.0.1 on 2022-01-20 07:13

import datetime

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("tasks", "0005_remove_recurringtask_database_id_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="recurringtask",
            name="owner",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="tasks",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="recurringtask",
            name="start_time",
            field=models.DateTimeField(
                default=datetime.datetime(2022, 1, 21, 7, 13, 31, 255740, tzinfo=utc)
            ),
        ),
    ]
