# Generated by Django 3.2.10 on 2021-12-25 17:47

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0005_alter_recurringtask_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='recurringtask',
            name='start_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
