# Generated by Django 3.2 on 2022-03-11 15:44

import datetime

import django.db.models.deletion
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ("workspaces", "0002_alter_notionworkspace_icon_url"),
        ("tasks", "0009_alter_recurringtask_start_time"),
    ]

    operations = [
        migrations.AddField(
            model_name="recurringtask",
            name="workspace",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="tasks",
                to="workspaces.notionworkspace",
            ),
        ),
        migrations.AlterField(
            model_name="recurringtask",
            name="start_time",
            field=models.DateTimeField(
                default=datetime.datetime(2022, 3, 12, 15, 44, 39, 656257, tzinfo=utc)
            ),
        ),
    ]
