# Generated by Django 3.2 on 2022-03-15 07:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("embed_widgets_base", "0001_initial"),
        ("notion_database", "__first__"),
    ]

    operations = [
        migrations.CreateModel(
            name="NotionDatabaseEmbed",
            fields=[
                (
                    "embeddable_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="embed_widgets_base.embeddable",
                    ),
                ),
                (
                    "notion_database",
                    models.OneToOneField(
                        blank=True,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="notion_database.notiondatabase",
                    ),
                ),
            ],
            bases=("embed_widgets_base.embeddable",),
        ),
        migrations.CreateModel(
            name="NotionEmbedPropertySettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "database_embed",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notion_property_settings",
                        to="notion_embeds.notiondatabaseembed",
                    ),
                ),
                (
                    "property",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="notion_database.notionpropertymetadata",
                    ),
                ),
            ],
        ),
    ]
