# Generated by Django 3.2 on 2022-03-17 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notion_embeds", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="notionembedpropertysettings",
            name="should_be_visible",
            field=models.BooleanField(default=True),
        ),
    ]
