# Generated by Django 3.2 on 2022-03-15 08:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notion_database", "__first__"),
        ("notion_embeds", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notiondatabaseembed",
            name="notion_database",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="notion_database.notiondatabase",
            ),
        ),
    ]
