# Generated by Django 3.2 on 2022-03-17 20:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notion_database", "0001_initial"),
        ("notion_embeds", "0003_delete_notionembedpropertysettings"),
    ]

    operations = [
        migrations.CreateModel(
            name="NotionEmbedPropertySettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("should_be_visible", models.BooleanField(default=True)),
                (
                    "database_embed",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notion_property_settings",
                        to="notion_embeds.notiondatabaseembed",
                    ),
                ),
                (
                    "property",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="notion_database.notionpropertymetadata",
                    ),
                ),
            ],
        ),
    ]
