# Generated by Django 3.2 on 2022-03-17 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("embed_widgets_base", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="embeddable",
            name="name",
            field=models.CharField(default="New Widget", max_length=255),
        ),
    ]
